INSERT INTO posts (id, text, image_url, author_id) VALUES (
 1, 'Insertion of Radioactive Element into Right Nipple, External Approach', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 5),
(2, 'Bypass Right Axillary Artery to Bilateral Upper Arm Artery, Open Approach', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 1),
(3, 'Occlusion of Jejunum, Percutaneous Endoscopic Approach', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 2),
(4, 'Restriction of Pancreatic Duct with Extraluminal Device, Open Approach', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 6),
(5, 'Revision of Synthetic Substitute in Right Tibia, Percutaneous Endoscopic Approach', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 5),
(6, 'Removal of Synthetic Substitute from Left Tarsal, Percutaneous Approach', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 1),
(7, 'Transfer Right Upper Leg Tendon, Open Approach', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 1),
(8, 'Reattachment of Right Large Intestine, Open Approach', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 10),
(9, 'Reposition Left Shoulder Joint with Internal Fixation Device, Percutaneous Endoscopic Approach', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 5),
(10, 'Drainage of Thoracic Vertebral Joint, Percutaneous Endoscopic Approach, Diagnostic', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 8),
(11, 'Occlusion of Right Radial Artery, Percutaneous Endoscopic Approach', 'http://dummyimage.com/100x100.png/dddddd/000000', 3),
(12, 'Supplement Left Tunica Vaginalis with Autologous Tissue Substitute, Percutaneous Endoscopic Approach', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 6),
(13, 'Restriction of Mesenteric Lymphatic with Extraluminal Device, Open Approach', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 8),
(14, 'Stereotactic Particulate Radiosurgery of Pelvis Lymphatics', 'http://dummyimage.com/100x100.png/dddddd/000000', 8),
(15, 'Revision of Nonautologous Tissue Substitute in Right Metatarsal, External Approach', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 8),
(16, 'Release Left Lower Extremity Bursa and Ligament, Open Approach', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 1);